### ISSUE TITLE
Nicer commit messages

### ISSUE THREAD

**Issue by asmarton** [RoundEnya/Probably-Infinite-Pointers#3]
Nu conteaza ca doar ati bagat pointeri pana la 666, e mai frumix "Increases pointer depth to 666" decat "p666". Mai ales la repouri serioase, va dau aia in cap daca puneti nume de-astea la commituri. Bafta @RoundEnya/cavalerii-mesei-rotunde , avem nevoie. Dati comm cu "Got it" sau "Am priceput" sau "Imi place tortul de ciocolata" sau ce vreti voi ca sa vad ca ati citit si sa inchid asta.

**Comment by brev404** [comment]
sure
